
import Wrapper from '@/components/shared/Wrapper';
import './globals.css';
import { Sora } from 'next/font/google'
import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/ui/Footer';


const sora = Sora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Wrapper>
          <Navbar />
          {children}
        </Wrapper>
        <Footer />
      </body>
    </html>
  )
}
